[tool.poetry]
name = "small-dev-teams-software"
version = "0.1.0"
description = ""
authors = ["Petr Stribny <petr@stribny.name"]

[tool.poetry.dependencies]
python = "^3.7"
Jinja2 = "^2.10.3"
pyppeteer = "^0.0.25"
click = "^7.0"
Pillow = "^7.0.0"
